### ISSUE TITLE
LoRaWAN_UnmarshalPacket 

### ISSUE THREAD

**Issue by bobmorane83** [lobaro/util-lorawan-packets#4]
Hi,

I think that you need to check of UNCONFIRMED and CONFIRMED in LoRaWAN_UnmarshalPacket

if (packet->MHDR.type == MTYPE_CONFIRMED_DATA_UP || packet->MHDR.type == MTYPE_UNCONFIRMED_DATA_UP) {

instead of

if (packet->MHDR.type == MTYPE_UNCONFIRMED_DATA_UP || packet->MHDR.type == MTYPE_UNCONFIRMED_DATA_UP) {

Sorry, no git at hand to commit,
BR,

**Comment by niondir** [comment]
Thanks for finding this. Seems legit, I will have a look.
