### ISSUE TITLE
base64 decoding

### ISSUE THREAD

**Issue by TheStudent227** [lobaro/util-lorawan-packets#6]
Hello, want to understand at what place the base64 decoder is placed.I am asking this, since  lorawan packets uses base64 format to transfer the data, but on AES128 input the data is decoded from base64. 
![base64_issue](https://user-images.githubusercontent.com/59653861/139590368-49f55e4d-8f10-442b-b220-39104768cc7a.png)

**Comment by niondir** [comment]
LoRaWAN packets are just bytes that can be represented as Base64 or HEX e.g. in many network servers. But a LoRaWAN implementation does not need to use Base64.

Please refer to the LoRaWAN spec to Unterstand the packet formats.
